# Generated by Django 5.2.2 on 2025-06-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='portfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=50)),
                ('boughtPrice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currentPrice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=10)),
                ('dailyProfit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
