# Generated by Django 5.2.2 on 2025-06-05 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioitem',
            name='currentPrice',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='dailyProfit',
        ),
    ]
