# Generated by Django 5.2.2 on 2025-06-05 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_portfolioitem_currentprice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioitem',
            name='name',
        ),
    ]
