# Generated by Django 5.2.2 on 2025-06-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_portfolioitem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='symbol',
            field=models.CharField(max_length=10),
        ),
    ]
